#This is development only compose!
name: receipt-splitting-bot-dev


services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_AUTH_METHOD: ${POSTGRES_AUTH_METHOD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


  bot:
    build: .
    environment:
      DATABASE_DSN: ${DATABASE_DSN?}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OCR_MODEL: ${OCR_MODEL}
      ASR_MODEL: ${ASR_MODEL}
      AGENT_MODEL: ${AGENT_MODEL}
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /receipt-splitting-bot/src
        - action: rebuild
          path: uv.lock
