name: receipt-splitting-bot-staging

services:
  bot:
    # image: ghcr.io/beavernotacat/receipt-splitting-bot:staging
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - key-value-store
      - pooler

  key-value-store:
    image: redis:8.6-alpine
    command: redis-server --save 300 1
    volumes:
      - redis_data:/data
    restart: unless-stopped

  pooler:
    image: edoburu/pgbouncer:latest
    environment:
      DATABASE_URL: ${POOLER_DATABASE_DSN?}
      POOL_MODE: transaction
      AUTH_TYPE: scram-sha-256
    restart: unless-stopped
    depends_on:
      - database
    
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
    volumes:
      - ./infra/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh:ro
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
