class DomainError(Exception): ...


class AssignNotToParticipantError(DomainError): ...


class NotDebtorError(DomainError): ...


class AlreadyParticipantError(DomainError): ...


class RemovedMoreThanExistError(DomainError): ...


class ItemNotInCollectionError(DomainError): ...
