name: Building and deployment

on:
  push:
    branches:
      - main
  pull_request: # on testing puroposes, DELETE THIS

permissions: read-all

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: beavernotacat
  REGISTRY_IMAGE_NAME: receipt-splitting-bot

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{env.REGISTRY_NAMESPACE}}/${{env.REGISTRY_IMAGE_NAME}}:staging
