name: Linting and tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions: read-all

env:
  UV_LOCKED: 1

jobs:
  ruff:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
      - run: uv run ruff format --check
      - run: uv run ruff check

  mypy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
      - run: uv run mypy .


  pytest:
    needs: [ruff, mypy]
    runs-on: ubuntu-latest
    env:
        DEBUG: true
        DATABASE_DSN: postgresql+psycopg://postgres:postgres@localhost:5432/receipt-splitting-bot
        KEY_VALUE_STORE_DSN: redis://localhost
        TELEGRAM_TOKEN: ...
        OPENROUTER_API_KEY: ...
        OCR_MODEL: ...
        ASR_MODEL: ...
        AGENT_MODEL: ...
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: receipt-splitting-bot
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
      - run: uv run alchemy --config src.adapters.database.cli_config.config upgrade --no-prompt
      - run: uv run pytest --cov=src --cov-report markdown:coverage.md
      - uses: actions/upload-artifact@v6
        with:
          name: coverage.md
          path: coverage.md
