name: Linting and tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions: read-all

env:
  UV_LOCKED: 1

jobs:
  ruff:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
      - run: uv run ruff check

  mypy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
      - run: uv run mypy .


  pytest:
    needs: [ruff, mypy]
    runs-on: ubuntu-latest
    env:
        DATABASE_DSN: postgresql+psycopg://postgres:postgres@localhost:5432/receipt-splitting-bot
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: receipt-splitting-bot
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
      - run: uv run alchemy --no-prompt --config src.adapters.database.cli_config.config upgrade
      - run: uv run pytest --cov=src --cov-report markdown:coverage.md
      - uses: actions/upload-artifact@v6
        with:
          name: coverage.md
          path: coverage.md        

  bandit:
    runs-on: ubuntu-slim
    needs: [ruff, mypy]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
        with:
            enable-cache: true
      - run: uv run bandit src -f yaml -o bandit.yaml
      - uses: actions/upload-artifact@v6
        with:
          name: bandit.yaml
          path: bandit.yaml
